name: Create Release

on:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'

jobs:
  check-version:
    runs-on: ubuntu-24.04
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if version changed
        id: check
        run: |
          OLD_VERSION=$(git show HEAD^:gradle.properties | grep "mod_version" | cut -d'=' -f2 | tr -d ' ')
          NEW_VERSION=$(grep "mod_version" gradle.properties | cut -d'=' -f2 | tr -d ' ')
          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "version=v$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-version
    if: needs.check-version.outputs.should_release == 'true'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Get Changelog
        id: changelog
        run: |
          if [ -f changelog.md ]; then
            echo "changelog=$(cat changelog.md)" >> $GITHUB_OUTPUT
          else
            echo "changelog=No changelog provided" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.check-version.outputs.version }}
          name: Release ${{ needs.check-version.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}